openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DocSpera/patient-survey-api/1.0.0
info:
  description: Intelligent Scheduling Dashboard APIs
  version: "1.0.0-alpha1"
  title: Intelligent Scheduling Dashboard
  x-logo:
    url: https://docspera.com/assets/D3/pic/Logo-Full-White-Padded.png
    backgroundColor: "#0096FA"
    href: https://docspera.com
  contact:
    email: luca@docspera.com
  license:
    name: Proprietary
tags:
  - name: physician
    x-displayName: "Authenticated Physician User"
    description: |
      apis available to an authenticated physician user
paths:
  /api/v1/intelligent-scheduling/policies:
    get:
      tags:
        - physician
      summary: Get prioiritization policies
      operationId: getPrioritizationPolicies
      responses:
        '200':
          description: policy list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrioritizationPolicy'
              examples:
                'policy list':
                  summary: policy list
                  value: [{"id":"5efbb8e20e20780692fb71af","title":"Standard","description":"Weighted heaviest equally by Pain, Funcationality, Fall Risk\nFollowed by decreasing weights for Number of Comorbidities, BMI and Days from Surgery","order":1,"category":"Case Urgency"},{"id":"5efbb9024abcf5dfe33c0547","title":"Disability","description":"Equally weighted by Pain, Funcationality and Fall Risk","order":2,"category":"Case Urgency"},{"id":"5efbb93a4ffa754b7270ee3f","title":"Complication","description":"Equally weighted by Age, BMI, and Number of Comorbidities","order":4,"category":"Outpatient"},{"id":"5efbb937a792b1247d81c9bb","title":"Physical Need","description":"Equally weighted by Pain, Funcationality, Fall Risk and Age\nFollowed by lower weight for Days from Surgery","order":3,"category":"Case Urgency"},{"id":"5efbb86ba27c7a558c6e4fff","title":"Days From Surgery","description":"","order":0,"category":"Case Urgency"}]

  /api/v1/intelligent-scheduling/preferences/policy:
    get:
      tags:
        - physician
      summary: Get prioiritization policy preference
      operationId: getPrioritizationPolicyPreference
      responses:
        '200':
          description: saved policy preference
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrioritizationPolicy'
              examples:
                'policy':
                  summary: policy
                  value:
                    {"id": "5efbb86ba27c7a558c6e4fff", "name": "Days From Surgery", "description": "", "category": "Case Urgency"}
    put:
      tags:
        - physician
      summary: Save prioiritization policy preference
      operationId: savePrioritizationPolicyPreference
      responses:
        '204':
          description: preference saved
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  description: policy id
            examples:
              'save policy':
                value: {"id": "5efbb86ba27c7a558c6e4fff"}

  /api/v1/intelligent-scheduling/patients:
    get:
      tags:
        - physician
      summary: Get patient priorities
      operationId: getPatientPriorities
      parameters:
        - name: limit
          in: query
          description: cursor pagination per page limit
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 100
            default: 50
          required: false
        - name: token
          in: query
          description: cursor pagination token
          schema:
            type: string
          required: false
        - name: policyid
          in: query
          description: prioritization policy override
          schema:
            type: string
          required: false
        - name: practiceId
          in: query
          description: practice id to show patients for. user must be a part of this practice or be an admin
          schema:
            type: integer
            format: int64
          required: false
        - name: userId
          in: query
          description: user id to show patients for. user must be a part of this practice or be an admin. defaults to the current user
          schema:
            type: integer
            format: int64
            description: ae2 encoded user id
          required: false
        - name: filterKey
          in: query
          description: column to filter results by
          schema:
            type: string
            description: filter key
          required: false
        - name: filterValue
          in: query
          description: value to filter results in filter column by
          schema:
            description: filter value
          required: false
        - name: sortBy
          in: query
          description: column to sort results by. this is applied after a filter
          schema:
            type: string
        - name: sort
          in: query
          description: order to sort reults by. this is applied in conjunction with `sortBy` and after a filter
          required: false
          schema:
            type: string
            enum: ["asc", "desc"]
            default: "desc"
            description: direction to sort by
      responses:
        '200':
          description: patients response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatientPriorityResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: bad_request
                description: invalid parameters
        '403':
          description: forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: forbidden
                description: unable to access specified resources
  /api/v1/intelligent-scheduling/patients/{patientId}:
    parameters:
      - name: patientId
        in: path
        description: patient id
        schema:
          type: integer
          format: int32
          description: docspera patient id
        required: true
    get:
      tags:
        - physician
      summary: Get patient priority
      operationId: getPatientPriority
      responses:
        '200':
          description: patient response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientPriorityResponse'
        '404':
          description: patient not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: not_found
                description: patient not found
        '403':
          description: forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: forbidden
                description: unable to access specified resources
    put:
      tags:
        - physician
      summary: Update patient priority
      operationId: updatePatientPriority
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  description: policy id
            examples:
              'save policy':
                value: {"id": "5efbb86ba27c7a558c6e4fff"}
      responses:
        '200':
          description: updated patient response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientPriorityResponse'
        '404':
          description: patient not found
          content:
            application/json:
              schema:
                type: object
                required:
                  - policyId
                  - priority
                properties:
                  policyId:
                    type: string
                    format: uuid
                    description: policy id used for computing priority
                  priority:
                    type: number
                    format: double
                    description: computer patient priority
        '403':
          description: forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: forbidden
                description: unable to access specified resources
components:
  securitySchemes:
    signedCookie:
      type: apiKey
      in: cookie
      name: docsperajwt
      description: docspera signed jwt cookie
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      required:
        - error
        - description
      properties:
        error:
          type: string
          description: error type
        description:
          type: string
          description: error_message
    PrioritizationPolicy:
      type: object
      required:
        - id
        - title
        - order
        - description
        - category
      properties:
        id:
          type: string
          description: policy id
        title:
          type: string
          description: name of policy
        order:
          type: number
          format: int32
          description: relative order
        description:
          type: string
          description: policy description
        category:
          type: string
          description: category of the policy
    PatientPriorityResponse:
      type: object
      required:
        - patientId
        - calendarId
        - name
        - dob
        - factors
        - priority
      properties:
        patientId:
          type: integer
          format: int32
          description: docspera patient id
        calendarId:
          type: integer
          format: int32
          description: docspera calendar id
        name:
          type: string
          description: patient name
        dob:
          type: string
          format: date
          description: patient date of birth
        factors:
          type: object
          required:
            - fallRisk
            - pain
            - functionality
            - daysFromSurgery
            - bmi
            - comorbidities
            - covid
          properties:
            fallRisk:
              type: number
              format: float
            pain:
              type: number
              format: float
            functionality:
              type: number
              format: float
            daysFromSurgery:
              type: integer
              format: int32
            bmi:
              type: number
              format: float
            comorbidities:
              type: array
              items:
                type: string
            covid:
              type: boolean
        priority:
          type: object
          required:
            - policyId
            - priority
          properties:
            policyId:
              type: string
              format: uuid
              description: policy id used for computing priority
            priority:
              type: number
              format: double
              description: computer patient priority


